import { useEffect, useState } from "react";

import type { CodeHighlighter, CodeToHtml } from "./types";

interface CreateShikiHighlighterOptions {
  /** Theme pair forwarded to `codeToHtml`. Defaults to GitHub light/dark. */
  themes?: { light: string; dark: string };
}

const DEFAULT_THEMES = { light: "github-light", dark: "github-dark" };

/**
 * Builds a {@link CodeHighlighter} from any `codeToHtml`-compatible function.
 *
 * This factory imports no Shiki bundle itself, so importing it never drags
 * highlighting code into your app. You decide which bundle to pay for by
 * passing the `codeToHtml` from `shiki` (full), `shiki/bundle/web` (web), or a
 * minimal `createHighlighterCore` instance.
 *
 * @example
 * import { codeToHtml } from "shiki/bundle/web";
 * const Highlighter = createShikiHighlighter(codeToHtml);
 * <LLMMessage highlighter={Highlighter}>{content}</LLMMessage>
 */
export function createShikiHighlighter(
  codeToHtml: CodeToHtml,
  options?: CreateShikiHighlighterOptions,
): CodeHighlighter {
  const themes = options?.themes ?? DEFAULT_THEMES;

  return function ShikiHighlighter({ code, language, className }) {
    const [html, setHtml] = useState<string | null>(null);

    useEffect(() => {
      let cancelled = false;
      Promise.resolve(codeToHtml(code, { lang: language, themes }))
        .then((result) => {
          if (!cancelled) setHtml(result);
        })
        .catch(() => {
          // Fallback: if the language is unsupported, just show plain code.
          if (!cancelled) setHtml(null);
        });
      return () => {
        cancelled = true;
      };
      // `codeToHtml` and `themes` are fixed for the lifetime of a highlighter
      // instance (captured from the factory closure), so they are intentionally
      // not listed: they never change between renders of this component.
    }, [code, language]);

    if (html) {
      return (
        <div
          className={className ?? "llm-shiki"}
          // The HTML is generated by Shiki, which is safe.
          dangerouslySetInnerHTML={{ __html: html }}
        />
      );
    }

    return <code className="llm-code-plain">{code}</code>;
  };
}
